### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###
### POST
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "name": "John Doe",
  "email": "mona@gmail.com"
}
###
GET http://localhost:3000/api/user
###
GET http://localhost:3000/api/user/2
###
PUT http://localhost:3000/api/user/2
Content-Type: application/json

{
  "name": "John Doe",
  "email": "mrrnee@gmail.com"
}

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "mrrnee011@gmail.com",
  "password": "1234568966"
}